# Generated by Django 3.2.6 on 2021-08-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmapp', '0003_auto_20210830_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('namei', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
