# Generated by Django 3.2.6 on 2021-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmapp', '0004_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=30)),
                ('head', models.CharField(max_length=30)),
                ('rev', models.CharField(max_length=300)),
            ],
        ),
    ]
