# Generated by Django 3.2.6 on 2021-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmapp', '0006_rename_rev_review_revi'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=30)),
                ('head', models.CharField(max_length=50)),
                ('revi', models.CharField(max_length=100)),
            ],
        ),
    ]
