# Generated by Django 3.2.6 on 2021-09-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsmapp', '0007_firstreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstreview',
            old_name='head',
            new_name='headf',
        ),
        migrations.RenameField(
            model_name='firstreview',
            old_name='img',
            new_name='imagef',
        ),
        migrations.RenameField(
            model_name='firstreview',
            old_name='name',
            new_name='namef',
        ),
        migrations.RenameField(
            model_name='firstreview',
            old_name='revi',
            new_name='revif',
        ),
    ]
